import java.io.IOException;

/*
 * 
 * This program is solution to the 1st task "Sorting" for Digital Design IT university.
 * In order to solve main task external merge sort was used.
 * In order to solve additional tasks Java 8 Stream API was used.
 * 
 * All logic in BigData class file.
 * 
 * Tested on 100mb randomly generated by UNIX file with setting maximum
 * memory usage of JVM to 60mb.
 * 
 * Samoylov Ilya
 * ilsv1721@gmail.com
 * 
 * Данная программа является решением 1 задачи о сортировке большого файла. 
 * В рамках данной задачи был имплементирован external merge sort алгоритм.
 * Для решения дополнительных задач по поиску строк использвался Java 8 Stream API. 
 * 
 * Самойлов Илья 
 * ilsv1721@gmail.com
 *  
 */
public class JustStarter {

	/**
	 * 
	 * Entering point
	 * 
	 * @param args;
	 *            args[1] - path to file which needed to be sorted; args[2] -
	 *            path to output sorted file;
	 * @throws IOException
	 */
	public static void main(String[] args) throws IOException {

		BigDataFile bigDataFile = new BigDataFile(args[0]);
		bigDataFile.externalSort("prefixTemp", "suffixTemp", args[1]);

		// Uncomment to check searching

		// bigDataFile.findStringWithSubstring("++++", System.out);
		// bigDataFile.findStringRegEx(Pattern.compile("\\+\\+\\+\\+"),
		// System.out);

	}
}
